In [ ]:
%tensorflow_version 1.x

In [ ]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

In [ ]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [ ]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [ ]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [ ]:
W = tf.Variable(tf.random_normal([4, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [ ]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [ ]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [ ]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [ ]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [ ]:
for step in range(101):
  cost_val, hy_val, _ = sess.run(
      [cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data}
  )
  print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  120882740000.0 
Prediction:
 [[246290.98]
 [494301.6 ]
 [389156.4 ]
 [273227.28]
 [321757.5 ]
 [324450.75]
 [297479.66]
 [378352.44]]
1 Cost:  1.3281147e+26 
Prediction:
 [[-8.1292244e+12]
 [-1.6364962e+13]
 [-1.2873725e+13]
 [-9.0244131e+12]
 [-1.0635753e+13]
 [-1.0725272e+13]
 [-9.8300823e+12]
 [-1.2515649e+13]]
2 Cost:  inf 
Prediction:
 [[2.6945411e+20]
 [5.4243877e+20]
 [4.2671698e+20]
 [2.9912634e+20]
 [3.5253640e+20]
 [3.5550360e+20]
 [3.2583135e+20]
 [4.1484809e+20]]
3 Cost:  inf 
Prediction:
 [[-8.9314194e+27]
 [-1.7979863e+28]
 [-1.4144109e+28]
 [-9.9149449e+27]
 [-1.1685293e+28]
 [-1.1783646e+28]
 [-1.0800119e+28]
 [-1.3750699e+28]]
4 Cost:  inf 
Prediction:
 [[2.9604393e+35]
 [5.9596680e+35]
 [4.6882560e+35]
 [3.2864424e+35]
 [3.8732482e+35]
 [3.9058486e+35]
 [3.5798453e+35]
 [4.5578548e+35]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]