In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable

torch.manual_seed(777) # for reproducibility

In [2]:
# X and Y data
x_data = [[73., 80., 75.], [93., 88., 93.],
          [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

In [3]:
# Our hypothesis XW+b
model = nn.Linear(3, 1, bias = True)

In [4]:
# cost criterion
criterion = nn.MSELoss()

In [5]:
# Minimize
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [6]:
# Train the model
for step in range(2001):
  optimizer.zero_grad()
  # Our hypothesis
  hypothesis = model(X)
  cost = criterion(hypothesis, Y)
  cost.backward()
  optimizer.step()

  if step % 10 == 0:
    print(step, "Cost: ", cost.data.numpy(), "\nPrediction:\n", hypothesis.data.numpy())

0 Cost:  50211.008 
Prediction:
 [[-44.56713 ]
 [-56.314262]
 [-54.078915]
 [-58.646557]
 [-43.865524]]
10 Cost:  6.1330004 
Prediction:
 [[153.63612]
 [181.9277 ]
 [180.65643]
 [196.97502]
 [137.85663]]
20 Cost:  5.6454573 
Prediction:
 [[154.22714]
 [182.65448]
 [181.36404]
 [197.74625]
 [138.41452]]
30 Cost:  5.6176424 
Prediction:
 [[154.2203 ]
 [182.66263]
 [181.36356]
 [197.7464 ]
 [138.42426]]
40 Cost:  5.5900164 
Prediction:
 [[154.21167]
 [182.66856]
 [181.36098]
 [197.74423]
 [138.43231]]
50 Cost:  5.5625153 
Prediction:
 [[154.20308]
 [182.67451]
 [181.35838]
 [197.74208]
 [138.44035]]
60 Cost:  5.535174 
Prediction:
 [[154.19447]
 [182.68042]
 [181.35577]
 [197.7399 ]
 [138.44833]]
70 Cost:  5.507951 
Prediction:
 [[154.18593]
 [182.68634]
 [181.3532 ]
 [197.73773]
 [138.45633]]
80 Cost:  5.4808993 
Prediction:
 [[154.17741]
 [182.69223]
 [181.35062]
 [197.7356 ]
 [138.46431]]
90 Cost:  5.4540205 
Prediction:
 [[154.16887]
 [182.69807]
 [181.34805]
 [197.73344]
 [138.47223]