In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

torch.manual_seed(777) # for reproducibility

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [3]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [4]:
x_data = Variable(torch.from_numpy(x_data))
y_data = Variable(torch.from_numpy(y_data))

In [5]:
# Our hypothesis XW+b
model = nn.Linear(3, 1, bias = True)

In [6]:
# cost criterion
criterion = nn.MSELoss()

In [7]:
# Minimize
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [8]:
# Train the model
for step in range(2001):
  optimizer.zero_grad()
  # Our hypothesis
  hypothesis = model(x_data)
  cost = criterion(hypothesis, y_data)
  cost.backward()
  optimizer.step()

  if step % 10 == 0:
    print(step, "Cost: ", cost.data.numpy(), "\nPrediction:\n", hypothesis.data.numpy())

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [175.50584]
 [172.87416]
 [167.45264]
 [155.46387]
 [190.73236]]
160 Cost:  10.53725 
Prediction:
 [[154.99945 ]
 [183.79169 ]
 [182.36893 ]
 [198.93689 ]
 [139.25443 ]
 [102.81875 ]
 [150.05307 ]
 [112.923256]
 [171.55258 ]
 [159.35358 ]
 [143.48898 ]
 [140.48497 ]
 [188.04953 ]
 [155.68237 ]
 [150.40013 ]
 [187.03923 ]
 [147.09567 ]
 [180.88834 ]
 [179.61209 ]
 [161.02713 ]
 [175.50908 ]
 [172.88104 ]
 [167.45319 ]
 [155.44443 ]
 [190.73177 ]]
170 Cost:  10.49778 
Prediction:
 [[154.99025]
 [183.79538]
 [182.3646 ]
 [198.93663]
 [139.25722]
 [102.82941]
 [150.05536]
 [112.92799]
 [171.5649 ]
 [159.37614]
 [143.491  ]
 [140.49518]
 [188.04079]
 [155.6697 ]
 [150.40514]
 [187.04585]
 [147.08278]
 [180.89049]
 [179.60075]
 [161.01619]
 [175.5123 ]
 [172.88792]
 [167.45375]
 [155.42508]
 [190.73119]]
180 Cost:  10.4586735 
Prediction:
 [[154.98106]
 [183.79904]
 [182.36028]
 [198.93636]
 [139.26   ]
 [102.84   ]
 [150.05763]
 [112.9327 ]
 [171.57713]


In [9]:
# Ask my score
print("Your score will be ", model(Variable(torch.Tensor([[100, 70, 101]]))).data.numpy())
print("Other scores will be ", model(Variable(torch.Tensor([[60, 70, 110], [90, 100, 80]]))).data.numpy())

Your score will be  [[182.73093]]
Other scores will be  [[176.84613]
 [178.33788]]
