In [1]:
import torch
from torch.autograd import Variable

torch.manual_seed(777) # for reproducibility

In [2]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5],
          [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

nb_classes = 3

In [3]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
softmax = torch.nn.Softmax()
linear = torch.nn.Linear(4, nb_classes, bias = True)
model = torch.nn.Sequential(linear, softmax)

In [4]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

In [5]:
for step in range(2001):
  optimizer.zero_grad()
  hypothesis = model(X)
  # Cross entropy cost/loss
  cost = -Y * torch.log(hypothesis)
  cost = torch.sum(cost, 1).mean()
  cost.backward()
  optimizer.step()

  if step % 200 == 0:
    print(step, cost.data.numpy())

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py:204: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


0 2.3687892
200 0.54633176
400 0.45158798
600 0.37642628
800 0.30450386
1000 0.24127777
1200 0.21791306
1400 0.19881797
1600 0.1826948
1800 0.1689059
2000 0.15698555


In [6]:
# Testing & One-hot encoding
print('--------------')
a = model(Variable(torch.Tensor([[1, 11, 7, 9]])))
print(a.data.numpy(), torch.max(a, 1)[1].data.numpy())

print('--------------')
b = model(Variable(torch.Tensor([[1, 3, 4, 3]])))
print(b.data.numpy(), torch.max(b, 1)[1].data.numpy())

print('--------------')
c = model(Variable(torch.Tensor([[1, 1, 0, 1]])))
print(c.data.numpy(), torch.max(c, 1)[1].data.numpy())

print('--------------')
all = model(Variable(torch.Tensor([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]])))
print(all.data.numpy(), torch.max(all, 1)[1].data.numpy())

--------------
[[7.6587736e-03 9.9233150e-01 9.6462936e-06]] [1]
--------------
[[0.8280986  0.15501654 0.01688482]] [0]
--------------
[[1.3566267e-08 3.5339006e-04 9.9964654e-01]] [2]
--------------
[[7.6587736e-03 9.9233150e-01 9.6462845e-06]
 [8.2809865e-01 1.5501647e-01 1.6884815e-02]
 [1.3566267e-08 3.5339006e-04 9.9964654e-01]] [1 0 2]
