In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Predicting animal type based on various features
xy = np.loadtxt('data-04-zoo.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [3]:
nb_classes = 7 # 0 ~ 6

In [4]:
# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1.

In [5]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units = nb_classes, input_dim = 16, activation = 'softmax'))

In [6]:
tf.model.compile(loss = 'categorical_crossentropy', optimizer = tf.keras.optimizers.SGD(lr = 0.1), metrics = ['accuracy'])

In [7]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7)                 119       
                                                                 
Total params: 119 (476.00 Byte)
Trainable params: 119 (476.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
history = tf.model.fit(x_data, y_one_hot, epochs = 1000)

Epoch 1/1000
4/4 [==============================] - 1s 9ms/step - loss: 2.5392 - accuracy: 0.0495
Epoch 2/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.3948 - accuracy: 0.0693
Epoch 3/1000
4/4 [==============================] - 0s 6ms/step - loss: 2.2871 - accuracy: 0.1683
Epoch 4/1000
4/4 [==============================] - 0s 6ms/step - loss: 2.1902 - accuracy: 0.3267
Epoch 5/1000
4/4 [==============================] - 0s 8ms/step - loss: 2.1103 - accuracy: 0.3762
Epoch 6/1000
4/4 [==============================] - 0s 13ms/step - loss: 2.0499 - accuracy: 0.3960
Epoch 7/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.0018 - accuracy: 0.4158
Epoch 8/1000
4/4 [==============================] - 0s 9ms/step - loss: 1.9549 - accuracy: 0.4158
Epoch 9/1000
4/4 [==============================] - 0s 22ms/step - loss: 1.9195 - accuracy: 0.4158
Epoch 10/1000
4/4 [==============================] - 0s 13ms/step - loss: 1.8872 - accuracy: 0.4158
Epoch 11/1000
4/

In [9]:
# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) # expected prediction == 3 (feathers)
print(tf.model.predict(test_data), np.argmax(tf.model.predict(test_data), axis = -1))

1/1 [==============================] - 0s 34ms/step
[[1.2641355e-02 1.8998213e-02 5.6074150e-02 8.7971574e-01 1.8816883e-02
  4.8511609e-04 1.3268453e-02]] [3]


In [10]:
# Full x_data test
pred = np.argmax(tf.model.predict(x_data), axis = -1)

for p, y in zip(pred, y_data.flatten()):
  print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

4/4 [==============================] - 0s 5ms/step
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 