In [1]:
import numpy as np
import tensorflow as tf

In [2]:
idx2char = ['h', 'i', 'e', 'l', 'o']
# Teach hello: hihell -> ihello
# x_data = [[0, 1, 0, 2, 3, 3]] # hihell
y_data = [[1, 0, 2, 3, 3, 4]] # ihello

In [3]:
num_classes = 5
input_dim = 5 # one-hot size, same as hidden_size to directly predict one-hot
sequence_length = 6 # |ihello| == 6
learning_rate = 0.1

In [4]:
x_one_hot = np.array([[[1, 0, 0, 0, 0], # h 0
                       [0, 1, 0, 0, 0], # i 1
                       [1, 0, 0, 0 ,0], # h 0
                       [0, 0, 1, 0, 0], # e 2
                       [0, 0, 0, 1, 0], # l 3
                       [0, 0, 0, 1, 0]]], # l 3
                     dtype = np.float32)

y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes = num_classes)
print(x_one_hot.shape)
print(y_one_hot.shape)

(1, 6, 5)
(1, 6, 5)


In [5]:
tf.model = tf.keras.Sequential()

# make cell and add it to RNN layer
# input_shape = (1,6,5) => number of sequence (batch), length of sequence, size of input dim
cell = tf.keras.layers.LSTMCell(units = num_classes, input_shape = (sequence_length, input_dim))
tf.model.add(tf.keras.layers.RNN(cell = cell, return_sequences = True))

# fully connected layer
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units = num_classes, activation = 'softmax')))

In [6]:
tf.model.compile(loss = 'categorical_crossentropy', optimizer = tf.keras.optimizers.Adam(lr = learning_rate),
                 metrics = ['accuracy'])

In [7]:
# train
tf.model.fit(x_one_hot, y_one_hot, epochs = 50)

Epoch 1/50
1/1 [==============================] - 5s 5s/step - loss: 1.6161 - accuracy: 0.1667
Epoch 2/50
1/1 [==============================] - 0s 18ms/step - loss: 1.6148 - accuracy: 0.1667
Epoch 3/50
1/1 [==============================] - 0s 17ms/step - loss: 1.6135 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 18ms/step - loss: 1.6122 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 17ms/step - loss: 1.6109 - accuracy: 0.3333
Epoch 6/50
1/1 [==============================] - 0s 19ms/step - loss: 1.6096 - accuracy: 0.3333
Epoch 7/50
1/1 [==============================] - 0s 18ms/step - loss: 1.6084 - accuracy: 0.3333
Epoch 8/50
1/1 [==============================] - 0s 18ms/step - loss: 1.6071 - accuracy: 0.3333
Epoch 9/50
1/1 [==============================] - 0s 16ms/step - loss: 1.6059 - accuracy: 0.3333
Epoch 10/50
1/1 [==============================] - 0s 17ms/step - loss: 1.6046 - accuracy: 0.3333
Epoch 11/50
1/1 [==============

In [8]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 rnn (RNN)                   (None, 6, 5)              220       
                                                                 
 time_distributed (TimeDist  (None, 6, 5)              30        
 ributed)                                                        
                                                                 
Total params: 250 (1000.00 Byte)
Trainable params: 250 (1000.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
predictions = tf.model.predict(x_one_hot)

for i, prediction in enumerate(predictions):
  print(prediction)
  # print char using argmax, dict
  result_str = [idx2char[c] for c in np.argmax(prediction, axis = 1)]
  print("\t Prediction str: ", ''.join(result_str))

1/1 [==============================] - 0s 196ms/step
[[0.2028903  0.17887199 0.2143928  0.20995218 0.19389269]
 [0.201662   0.18107739 0.21092425 0.21084285 0.19549356]
 [0.20391156 0.16808328 0.2258795  0.20585793 0.1962677 ]
 [0.20523943 0.1804418  0.21473265 0.21153225 0.18805382]
 [0.18951093 0.17928404 0.20028003 0.22213216 0.20879279]
 [0.17484833 0.17996706 0.1866749  0.22735311 0.23115659]]
	 Prediction str:  eeeelo
