In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter = ',')
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print('x_data', x_data)
print('y_data', y_data)

x_data [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
y_data [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [3]:
model = Sequential()
model.add(Dense(input_dim = 3, units = 1))

In [4]:
model.compile(loss = 'mse', optimizer = 'rmsprop')
model.fit(x_data, y_data, epochs = 2000)

Epoch 1/2000
1/1 [==============================] - 0s 377ms/step - loss: 22516.6797
Epoch 2/2000
1/1 [==============================] - 0s 11ms/step - loss: 22286.3125
Epoch 3/2000
1/1 [==============================] - 0s 11ms/step - loss: 22120.3359
Epoch 4/2000
1/1 [==============================] - 0s 14ms/step - loss: 21982.0371
Epoch 5/2000
1/1 [==============================] - 0s 10ms/step - loss: 21859.7676
Epoch 6/2000
1/1 [==============================] - 0s 12ms/step - loss: 21748.1172
Epoch 7/2000
1/1 [==============================] - 0s 13ms/step - loss: 21644.0820
Epoch 8/2000
1/1 [==============================] - 0s 11ms/step - loss: 21545.7793
Epoch 9/2000
1/1 [==============================] - 0s 9ms/step - loss: 21451.9648
Epoch 10/2000
1/1 [==============================] - 0s 17ms/step - loss: 21361.7480
Epoch 11/2000
1/1 [==============================] - 0s 10ms/step - loss: 21274.4824
Epoch 12/2000
1/1 [==============================] - 0s 8ms/step - loss: 2

In [5]:
print('0, 2, 1', model.predict(np.array([[0, 2, 1]])))
print('0, 9, -1', model.predict(np.array([[0, 9 ,-1]])))

1/1 [==============================] - 0s 143ms/step
0, 2, 1 [[2.1704707]]
1/1 [==============================] - 0s 39ms/step
0, 9, -1 [[3.6566]]
