In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [2]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [3]:
# very important. It does not work without it.
scaler = MinMaxScaler(feature_range = (0, 1))
xy = scaler.fit_transform(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [4]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [5]:
model = Sequential()
model.add(Dense(1, input_dim = 4))
model.add(Activation('linear'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 5         
                                                                 
 activation (Activation)     (None, 1)                 0         
                                                                 
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(loss = 'mse',
              optimizer = 'sgd',
              metrics = ['accuracy'])

In [8]:
history = model.fit(x_data, y_data, epochs = 100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.0796 - accuracy: 0.1250
Epoch 2/100
1/1 [==============================] - 0s 15ms/step - loss: 0.0766 - accuracy: 0.1250
Epoch 3/100
1/1 [==============================] - 0s 15ms/step - loss: 0.0737 - accuracy: 0.1250
Epoch 4/100
1/1 [==============================] - 0s 14ms/step - loss: 0.0711 - accuracy: 0.1250
Epoch 5/100
1/1 [==============================] - 0s 13ms/step - loss: 0.0686 - accuracy: 0.1250
Epoch 6/100
1/1 [==============================] - 0s 12ms/step - loss: 0.0663 - accuracy: 0.1250
Epoch 7/100
1/1 [==============================] - 0s 13ms/step - loss: 0.0642 - accuracy: 0.1250
Epoch 8/100
1/1 [==============================] - 0s 13ms/step - loss: 0.0622 - accuracy: 0.1250
Epoch 9/100
1/1 [==============================] - 0s 18ms/step - loss: 0.0604 - accuracy: 0.1250
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 0.0586 - accuracy: 0.1250
Epoch 11/100
1/1 [===

In [9]:
predictions = model.predict(x_data)
score = model.evaluate(x_data, y_data)

1/1 [==============================] - 0s 212ms/step - loss: 0.0250 - accuracy: 0.2500


In [10]:
print('Prediction: \n', predictions)
print('Cost: ', score[0])

Prediction: 
 [[0.67257816]
 [0.8316422 ]
 [0.6719585 ]
 [0.4266076 ]
 [0.61398995]
 [0.50392896]
 [0.38245177]
 [0.13496923]]
Cost:  0.024961551651358604
