In [1]:
from keras.models import Sequential
from keras.layers import Dense, TimeDistributed, Activation, LSTM
from keras.utils import np_utils

import numpy as np
import os

In [2]:
# sample text
sample = 'hihello'

char_set = list(set(sample)) # id -> char ['i', 'l', 'e', 'o', 'h']
char_dic = {w: i for i, w in enumerate(char_set)}

x_str= sample[:-1]
y_str = sample[1:]

data_dim = len(char_set)
timesteps = len(y_str)
num_classes = len(char_set)

print(x_str, y_str)

hihell ihello


In [3]:
x = [char_dic[c] for c in x_str] # char to index
y = [char_dic[c] for c in y_str] # char to index

In [4]:
# One-hot encoding
x = np_utils.to_categorical(x, num_classes = num_classes)
# reshape X to be [samples, time steps, features]
x = np.reshape(x, (-1, len(x), data_dim))
print(x.shape)

(1, 6, 5)


In [5]:
# One-hot encoding
y = np_utils.to_categorical(y, num_classes = num_classes)
# time steps
y = np.reshape(y, (-1, len(y), data_dim))
print(y.shape)

(1, 6, 5)


In [6]:
model = Sequential()
model.add(LSTM(num_classes, input_shape = (timesteps, data_dim),
               return_sequences = True))
model.add(TimeDistributed(Dense(num_classes)))
model.add(Activation('softmax'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 6, 5)              220       
                                                                 
 time_distributed (TimeDistr  (None, 6, 5)             30        
 ibuted)                                                         
                                                                 
 activation (Activation)     (None, 6, 5)              0         
                                                                 
Total params: 250
Trainable params: 250
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss = 'categorical_crossentropy',
              optimizer = 'rmsprop',
              metrics = ['accuracy'])

In [9]:
model.fit(x, y, epochs = 1)

1/1 [==============================] - 6s 6s/step - loss: 1.5823 - accuracy: 0.3333


In [10]:
predictions = model.predict(x, verbose = 0)

for i, prediction in enumerate(predictions):
  print(prediction)
  x_index = np.argmax(x[i], axis = 1)
  x_str = [char_set[j] for j in x_index]
  print(x_index, ''.join(x_str))

  index = np.argmax(prediction, axis = 1)
  result = [char_set[j] for j in index]
  print(index, ''.join(result))

[[0.20791964 0.18805887 0.20021816 0.21580783 0.1879955 ]
 [0.19831677 0.20026828 0.20059866 0.2085572  0.1922591 ]
 [0.20554216 0.18853211 0.20110416 0.22356513 0.18125643]
 [0.22414885 0.18929553 0.19730458 0.22537678 0.16387427]
 [0.2111062  0.20015071 0.2047681  0.20028436 0.18369053]
 [0.20890169 0.21249492 0.20184596 0.18289644 0.19386095]]
[2 1 2 3 0 0] hihell
[3 3 3 3 0 1] eeeeli
